-- Create documents table for blob storage
CREATE TABLE IF NOT EXISTS documents (
    id BIGSERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_extension VARCHAR(50),
    file_size BIGINT NOT NULL,
    data BYTEA NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uploaded_by BIGINT NOT NULL,
    description TEXT,
    CONSTRAINT fk_documents_user FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE CASCADE
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_by ON documents(uploaded_by);
CREATE INDEX IF NOT EXISTS idx_documents_uploaded_at ON documents(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_original_file_name ON documents(original_file_name);

-- Add comments for documentation
COMMENT ON TABLE documents IS 'Table for storing uploaded documents as binary data';
COMMENT ON COLUMN documents.file_name IS 'Unique filename generated by the system (UUID-based)';
COMMENT ON COLUMN documents.original_file_name IS 'Original filename as uploaded by the user';
COMMENT ON COLUMN documents.content_type IS 'MIME type of the uploaded file';
COMMENT ON COLUMN documents.file_extension IS 'File extension extracted from the original filename';
COMMENT ON COLUMN documents.file_size IS 'Size of the file in bytes';
COMMENT ON COLUMN documents.data IS 'Binary data of the uploaded file';
COMMENT ON COLUMN documents.uploaded_at IS 'Timestamp when the document was uploaded';
COMMENT ON COLUMN documents.uploaded_by IS 'ID of the user who uploaded the document';
COMMENT ON COLUMN documents.description IS 'Optional description provided by the user';
